### PR TITLE
fix: properly handle release version comparison with qualifier

### PR DESCRIPTION
**Pull request by tpetillot**
:warning: We should be able to do better later on...

### CODE REVIEW

**Review by slandelle — CHANGES_REQUESTED** [review]
No idea what this is supposed to fix as:
* no commit description
* no tests

**Comment by slandelle** [comment]
Should this PR be dropped?

**Comment by Isammoc** [comment]
Totally forgot that :sob:

**Comment by Isammoc** [comment]
superseded by sbt-dynver

**Pull request closed without merging**
